name:  Build and Test

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        os: [a, b]
        python: [37, 310]
        include:
          - python: 37
            numpyver: '1.20'
          - python: 310
            numpyver: '1.22'
    env:
      NUMPYVER: ${{ matrix.numpyver }}
    steps:
      - run: |
          echo "${{ matrix.os }} @ ${{ matrix.python }} @ ${{ matrix.numpyver }}"
      - run: |
          python -m pip install numpy==${{ matrix.numpyver }}
