name:  Build and Test

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - python: 3.7
            numpyver: 1.20
          - python: 3.10
            numpyver: 1.22
    env:
      NUMPYVER: ${{ matrix.numpyver }}
    steps:
      - run: |
          echo "$NUMPYVER"
